#!/usr/bin/env python3
"""Hermes feature parity report, generated from source (never hand-edited).

Every JSON-RPC method in the Hermes gateway contract and every HTTP route in
the Hermes Python routers is listed with its status in the sovereign engine:

  working      real behaviour backed by the engine
  placeholder  answers within the contract but reports the feature as
               off/empty until its module lands (the desktop degrades cleanly)
  missing      answers `not_supported_by_engine` (logged once per process)

Usage: scripts/parity.py [HERMES_AGENT_DIR] > docs/PARITY.md
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ENGINE = Path(__file__).resolve().parent.parent
HERMES = Path(sys.argv[1] if len(sys.argv) > 1 else ENGINE.parent / "hermes-agent")

# Answered honestly as "off / empty" until the named module is built.
PLACEHOLDER = {
    "free_tier.status", "wake.status", "pet.info", "projects.tree", "subagent.list",
    "process.list", "session.control.read", "profiles.list", "session.active_list",
}
# Where each missing namespace gets built (docs/SOVEREIGN_PLAN.md modules).
PLAN = {
    "bot_relay": "M10 channels (ZeroClaw)", "connectors": "M10 channels (ZeroClaw)",
    "cron": "M10 cron (ZeroClaw)", "profiles": "M10 profiles", "pet": "M10 pet",
    "voice": "M10 voice", "wake": "M10 voice", "skills": "M10 skills hub",
    "groups": "M10 group chats", "projects": "M10 projects", "vault": "M10 vault",
    "mcp": "M10 MCP management", "browser": "M10 browser pane", "display": "M10 display",
    "billing": "not applicable (hosted billing)", "subscription": "not applicable (hosted billing)",
    "free_tier": "not applicable (hosted free tier)", "learning": "M9/M10 learning views",
    "spawn_tree": "M9 observability", "subagent": "M9 observability", "delegation": "M9 observability",
    "handoff": "M10 handoff", "image": "M10 images", "rollback": "M10 rollback",
}


def rpc_methods_handled() -> set[str]:
    src = (ENGINE / "crates/sovereign-gateway/src/rpc.rs").read_text()
    body = src[src.index("async fn dispatch("):]
    body = body[: body.index("_ => {")]
    handled = set()
    for arm in re.findall(r'^\s*((?:"[a-z_.]+"\s*\|\s*)*"[a-z_.]+")\s*=>', body, re.M):
        handled.update(re.findall(r'"([a-z_.]+)"', arm))
    return handled


def rest_routes_handled() -> set[tuple[str, str]]:
    src = (ENGINE / "crates/sovereign-gateway/src/lib.rs").read_text()
    return set(re.findall(r'\("(GET|POST|PUT|DELETE|PATCH)", "(/api/[^"]+)"\)', src)) | {("GET", "/api/ws")}


def hermes_rest_routes() -> list[tuple[str, str, str]]:
    routes = []
    for py in sorted((HERMES / "hermes_cli/web_routers").glob("*.py")):
        for method, path in re.findall(r'@\w*router\.(get|post|put|delete|patch)\(\s*"(/api/[^"]+)"', py.read_text()):
            routes.append((method.upper(), path, py.stem))
    return routes


def main() -> None:
    contract = json.loads((ENGINE / "crates/sovereign-gateway/contract/gateway-contract.openrpc.json").read_text())
    methods = sorted(m["name"] for m in contract["methods"])
    handled = rpc_methods_handled()
    status = {m: ("placeholder" if m in PLACEHOLDER else "working") if m in handled else "missing" for m in methods}
    by_ns = defaultdict(list)
    for m in methods:
        by_ns[m.split(".")[0]].append(m)
    counts = defaultdict(int)
    for s in status.values():
        counts[s] += 1

    out = ["# Hermes feature parity (generated by scripts/parity.py)", ""]
    out.append("Nothing in Hermes is removed: the desktop is unmodified, and every method below is either handled "
               "or answers `not_supported_by_engine` so the UI degrades instead of breaking. Missing items are "
               "scheduled in `docs/SOVEREIGN_PLAN.md`.")
    out.append("")
    out.append(f"**JSON-RPC methods ({len(methods)}):** {counts['working']} working, {counts['placeholder']} placeholder, "
               f"{counts['missing']} missing. Events emitted: message.start/delta/complete, reasoning.delta, tool.start/"
               "complete, session.usage, session.title, status.update, error, gateway.ready. Server requests: approval.")
    out.append("")
    out.append("| Namespace | Working | Placeholder | Missing | Planned in |")
    out.append("|---|---|---|---|---|")
    for ns in sorted(by_ns):
        ms = by_ns[ns]
        pick = lambda s: ", ".join(f"`{m}`" for m in ms if status[m] == s) or "–"
        plan = PLAN.get(ns, "M10 parity") if any(status[m] == "missing" for m in ms) else ""
        out.append(f"| {ns} | {pick('working')} | {pick('placeholder')} | {pick('missing')} | {plan} |")

    rest = hermes_rest_routes()
    served = rest_routes_handled()
    rest_done = [r for r in rest if (r[0], r[1]) in served]
    out.append("")
    out.append(f"**HTTP routes in Hermes ({len(rest)}):** {len(rest_done)} served by the engine; the rest answer "
               "404 `not_supported_by_engine` (the desktop has fallbacks for missing routes).")
    out.append("")
    out.append("| Router | Served | Not yet |")
    out.append("|---|---|---|")
    by_router = defaultdict(list)
    for r in rest:
        by_router[r[2]].append(r)
    for router in sorted(by_router):
        rs = by_router[router]
        done = [f"`{m} {p}`" for m, p, _ in rs if (m, p) in served]
        todo = [f"`{m} {p}`" for m, p, _ in rs if (m, p) not in served]
        out.append(f"| {router} | {', '.join(done) or '–'} | {', '.join(todo) or '–'} |")
    print("\n".join(out))


if __name__ == "__main__":
    main()
